### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by andersevenrud**
You forgot about me ;)

### CODE REVIEW

**Comment by basicallydan** [comment]
Hahaha I did didn't I? I'm so sorry Anders! I'll merge later when I'm at a
computer :) please forgive me!

**Comment by andersevenrud** [comment]
No worries ;) I forgot about it myself, but came back to me when I started playing it out of boredom. It's kinda addictive! :smile:

**Comment by basicallydan** [comment]
@andersevenrud I agree! I really want to implement more features at some point and make it even more fun but these things take time :(

**Comment by andersevenrud** [comment]
Weeeh :)

**Comment by basicallydan** [comment]
@andersevenrud Hahaha! You are fast man!

**Comment by andersevenrud** [comment]
Indeed! :)

**Comment by andersevenrud** [comment]
That's what she said ? ;)

**Comment by basicallydan** [comment]
Hah! I hope not!

**Pull request merged**
